# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official

# Disable KSP2 for now as it may cause issues with Room 2.6.1
ksp.useKSP2=false

# Standard AndroidX flags
android.useAndroidX=true
android.nonTransitiveRClass=true
android.disallowKotlinSourceSets=false